services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: chat-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - chat-network

  # Backend service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: chat-backend
    ports:
      - "4000:4000"
    environment:
      - MONGO_URL=mongodb://admin:password@mongodb:27017
      - NODE_ENV=development
    depends_on:
      - mongodb
    networks:
      - chat-network
    volumes:
      - .:/app
      - /app/node_modules

  # Frontend service  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: chat-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - chat-network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongodb_data:

networks:
  chat-network:
    driver: bridge
